import GlassCard from "@/components/custom-ui/GlassCard"
import ThemeBgImage from "@/components/custom-ui/ThemeBgImage"
import DesktopHeader from "@/components/layout/DesktopHeader"
import HorizontalNav from "@/components/layout/HorizontalNav"
import Sidebar from "@/components/layout/Sidebar"
import type { Metadata } from "next"
import { Gentium_Book_Plus } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const gentium = Gentium_Book_Plus({
	subsets: ["latin"],
	weight: ["400", "700"],
})

const briemBold = localFont({
	src: "../../public/fonts/BriemHand-Bold.ttf",
	variable: "--briem-bold-font",
	display: "swap",
})
const briemRegular = localFont({
	src: "../../public/fonts/BriemHand-Regular.ttf",
	variable: "--briem-regular-font",
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="darks">
			<body
				className={`${gentium.className} ${briemBold.variable} ${briemRegular.variable} antialiased`}
			>
				<main className="relative h-screen w-screen p-4">
					<ThemeBgImage />
					<div className="flex gap-6 justify-between sm:max-lg:flex-wrap-reverse w-full h-full">
						<GlassCard classes="lg:w-1/6 h-full">
							<Sidebar />
						</GlassCard>

						<div className="right max-lg:w-full lg:flex-1 max-h-screen overflow-hidden">
							<div className="max-lg:sticky top-0 z-80 max-lg:backdrop-blur-sm p-4 pb-0 max-lg:mb-6 -mx-4 flex  flex-col gap-4 max-lg:bg-light-primary/20">
								<DesktopHeader />
								<HorizontalNav />
							</div>
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	)
}
