import type { Metadata } from "next"
import { Gentium_Book_Plus } from "next/font/google"
import "./globals.css"

const gentium = Gentium_Book_Plus({
	subsets: ["latin"],
	weight: ["400", "700"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="darks">
			<body className={`${gentium.className} antialiased`}>{children}</body>
		</html>
	)
}
